### ISSUE TITLE
Edge browser not detected

### ISSUE THREAD

**Issue by HuzaifaShakir** [metoikos/node-user-agents#3]
Edge browser is not getting detected. Below are the cases I have tested.

1. 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299',
2. 'Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.14977'

Change proposed:

Add "else if (this.userAgent.family.indexOf('Edge') > -1) return 'Edge';" condition in the getBrowser method.

**Comment by metoikos** [comment]
Thank you for your recommendation. I added your line and added few tests and it seems all OK.
